# Dockerfile to create Rosa linux 2014.1 base images
# Create base image: mkimage-urpmi.sh -s --version=2014.1 --mirror="--mirrorlist http://mirror.yandex.ru/rosa/rosa2014.1/rosa2014.1.i586.list"
#

FROM scratch
MAINTAINER "Gagarin Fedor" <fddgagarin@gmail.com>
ADD rootfs-systemd.tar.xz /
